### PR TITLE
Receive permission node feature (bukkit)

### PR DESCRIPTION
**Pull request by AaronPBCraft**
This PR is a suggestion of how to implement the requested perm in issue #23 using Vault's API which already provides offline-user perm checkings.
I hope it will be helpful to fully integrate it into the plugin :)

### CODE REVIEW

**Comment by YiC200333** [comment]
Thanks for your help, but I found that it still can't detect the permissions of offline players
If player is offline, the result of this code `XConomy.vaultPerm.playerHas(null, Bukkit.getOfflinePlayer(targetUUID), "xconomy.user.receive")` always return `False`. Whether the player has this permission

My tested server: Spigot 1.15.2, Vault 1.7.3

**Comment by AaronPBCraft** [comment]
I have tested this version of the plugin on a 1.16.4 spigot server and on a 1.16.4 paper server, along with vault(1.7.3) and luckperms and it works perfectly.
If the player has the xconomy.user.receive node set to false globally, no money is given (MinExilon has no extra perms)
image

**Comment by YiC200333** [comment]
I tested again. This function is normal working after installing luckperms

**Comment by AaronPBCraft** [comment]
Hmmm, it seems that Vault depends on a permissions manager plugin such as luckperms (or internal storage) to handle this check... I tested it without luckperms and I got the same as you, it returns always `False` if the player is not online.
According to the [Vault documentation](https://milkbowl.github.io/VaultAPI/net/milkbowl/vault/permission/Permission.html#playerHas-java.lang.String-org.bukkit.OfflinePlayer-java.lang.String-): _"Checks if player has a permission node. Supports NULL value for World if the permission system registered supports global permissions. But May return odd values if the servers registered permission system does not have a global permission store."_

**Comment by AaronPBCraft** [comment]
This solves the issue when Vault does not hook into a valid permission manager (it simply avoids the receive perm check, both for offline and online players).
If there are more permission managers that can handle offline player permissions, they can be added in the private method `checkVaultOfflinePermManager()` of the `XConomy` class.
It may be a bit more messy, but it avoids the problem that Vault has :smile:

Successfully tested with: Spigot 1.16.4, Vault 1.7.3 (with and without LuckPerms)

**Comment by YiC200333** [comment]
Thanks, It's a bit of a mess😄

**Pull request merged**
